### ISSUE TITLE
Fix repository file structure for improved clarity

### ISSUE THREAD

**Issue by Aedrus** [YSTEMandChess/react#15]
The React repository should be reset so that the entry point on GitHub begins at the **"react-ystemandchess"** folder level for clarity. For whoever does this, it should be a simple fix but the team will need to be notified when it happens so we are all on the same page.

**Comment by ChloeWKY** [comment]
Seems that the current organization is fine combined with other backend and server components.

Further details in #17.

**Comment by Aedrus** [comment]
@ChloeWKY 
Hi Chloe, you're right that most of the current organization is fine. However, this issue refers to simply moving the repository one level down in the file directory so that the repository entrypoint is at **"react-ystemandchess"** instead. This would be a simple QOL change for clarity and to make it easier to navigate for new contributors.
